name: Dummy/Mock Code Killer

on:
  push:
    paths:
      - 'src/**'
      - 'scripts/ci/check_no_dummy_code.sh'
      - '.github/workflows/dummy-code-check.yml'
  pull_request:
    paths:
      - 'src/**'
      - 'scripts/ci/check_no_dummy_code.sh'
      - '.github/workflows/dummy-code-check.yml'

jobs:
  dummy-code-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ripgrep
        run: sudo apt-get update && sudo apt-get install -y ripgrep

      - name: Run dummy/mock/fake code scan
        run: |
          chmod +x scripts/ci/check_no_dummy_code.sh
          bash scripts/ci/check_no_dummy_code.sh

      - name: Upload dummy code report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dummy_references.log
          path: reports/dummy_references.log

      - name: Notify Slack on Dummy Code Detection
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"🚨 Dummy/mock code detected in PR/Push. Build failed. Check reports/dummy_references.log for details."}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
